[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.gd",
  "php83Extensions.zip",
  "php83Extensions.pdo",
  "php83Extensions.mbstring",
  "php83Extensions.xml",
  "php83Extensions.curl",
  "php83Extensions.dom",
  "php83Extensions.tokenizer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-scripts --no-interaction"
]

[phases.postBuild]
cmds = [
  "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/logs bootstrap/cache",
  "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"